export const enum UNBLOCKING_HANDLER_TYPE {
  OPEN_CREATING_VIEW="OPEN_CREATING_VIEW",
  OPEN_YOUTUBE = "OPEN_YOUTUBE",
  CATEGORY_CREATE = "CATEGORY_CREATE",
  ROUTE = "ROUTE",
  SYSTEM_VOLUME = "SYSTEM_VOLUME",
}